apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: my-database
  name: my-database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: my-database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: my-database
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: my_wp_database
        - name: MYSQL_PASSWORD
          value: my_wp_user_password
        - name: MYSQL_ROOT_PASSWORD
          value: my_password_1234789
        - name: MYSQL_USER
          value: my_wp_user
        image: mysql
        imagePullPolicy: ""
        name: my-database
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql
status: {}
