apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: wordpress
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: my-database
        - name: WORDPRESS_DB_NAME
          value: my_wp_database
        - name: WORDPRESS_DB_PASSWORD
          value: my_wp_user_password
        - name: WORDPRESS_DB_USER
          value: my_wp_user
        image: wordpress:latest
        imagePullPolicy: ""
        name: wordpress
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: wordpress-claim0
        persistentVolumeClaim:
          claimName: wordpress-claim0
status: {}
